In [49]:
from random import randint
import numpy as np
import heapq

def get_zero_by_tenth_of(num):
    return 0 if randint(1, 10) <= num else 1 # 生成 0 的概率分别为 num/10

def create_maze(m, n):
    return [[get_zero_by_tenth_of(7) for j in range(n)] for i in range(m)]

def manhattan(cur, dest):
    return abs(dest[0] - cur[0]) + abs(dest[1] - cur[1])

def neighbors(cur, maze):
    i, j = cur
    m, n = len(maze), len(maze[0])
    neis = [(1, 0), (-1, 0), (0, 1), (0, -1)]
    for di, dj in neis:
        x, y = i+di, j+dj
        if 0 <= x < m and 0 <= y < n and maze[x][y] == 0:
            yield x, y

def trace_to_dest(visited, dest):
    path = [dest]
    while visited[dest]:
        pre = visited[dest]
        path.append(pre)
        dest = pre
    return path[::-1]            

def astar(maze, dest=(len(maze)-1, len(maze[0])-1)):
    m, n = len(maze), len(maze[0])
    start = (0, 0)
    heap = [(manhattan(start, dest), start)]
    visited = {start:None}
    while heap:
        depth_manhattan, cur = heapq.heappop(heap)
        if cur == dest:
            break
        depth = depth_manhattan - manhattan(cur, dest)
        for nei in neighbors(cur, maze):
            if nei not in visited:
                visited[nei] = cur
                heapq.heappush(heap, (depth + 1 + manhattan(nei, dest), nei))
    if dest not in visited:
        print("There is no way out!!!")
        return 
    path = trace_to_dest(visited, dest)
    return path

def path_in_maze(maze, path):
    for i, j in path:
        maze[i][j] = 2

In [58]:
maze = create_maze(20, 20)
maze[0][0] = maze[-1][-1] = 0
tmp = np.asarray(maze)
print(tmp)
path = astar(maze)
# print(np.asarray(path))
# sub_path = astar(maze, path[10])
# print(sub_path == path[:11])

path_in_maze(maze, path)
tmp = np.asarray(maze)
print(tmp)

[[0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1]
 [0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0]
 [0 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0]
 [0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1]
 [0 1 0 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 1 1]
 [0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 0 0 0 1 1]
 [0 0 0 1 1 0 1 1 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 1 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0]
 [1 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 1 1 0 0 0 0 0 1 1 1 0]
 [0 0 0 1 0 1 0 1 1 0 0 1 0 0 0 0 0 0 0 1]
 [1 0 1 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1]
 [1 0 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0]
 [1 0 0 1 1 0 1 1 0 0 1 0 1 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 1]
 [0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0]
 [1 0 1 0 1 0 0 1 1 1 1 0 0 1 1 0 0 0 0 0]
 [0 0 0 0 0 0 1 1 0 0 0 0 0 1 1 1 0 0 1 0]
 [0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0]]
[[2 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0 0 0 1 1]
 [2 0 1 1 0 0 0 1 1 1 0 0 0 0 1 0 0 1 1 0]
 [2 1 1 0 0 0 0 0 1 0 0 0 1 0 0 1 1 0 0 0]
 [2 0 0 1 